sudo: required
services:
  - docker

before_install:
  - docker build -t adnanmayo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adnanmayo/react-test npm test -- --coverage

after_success:
  - docker build -t adnanmayo/multi-client ./client
  - docker build -t adnanmayo/multi-nginx ./nginx
  - docker build -t adnanmayo/multi-server ./server
  - docker build -t adnanmayo/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push adnanmayo/multi-client
  - docker push adnanmayo/multi-nginx
  - docker push adnanmayo/multi-server
  - docker push adnanmayo/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: muti-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-076768706203
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


  

